# Discovery is shared by the Sprig build and the standalone integration check.
set(bloom_root "${CMAKE_CURRENT_SOURCE_DIR}/../Bloom")
set(bloom_generated "${CMAKE_CURRENT_BINARY_DIR}/bloom-modules.cpp")
set(bloom_assets "${CMAKE_CURRENT_BINARY_DIR}/bloom-assets")
file(REMOVE_RECURSE "${bloom_assets}")
file(MAKE_DIRECTORY "${bloom_assets}")
set(bloom_entries "")
file(GLOB bloom_manifests CONFIGURE_DEPENDS "${bloom_root}/*/bloom.ini")
foreach(manifest IN LISTS bloom_manifests)
    get_filename_component(module_dir "${manifest}" DIRECTORY)
    get_filename_component(module_name "${module_dir}" NAME)
    if(module_name MATCHES "^_" OR NOT module_name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
        message(WARNING "Bloom: skipping reserved or invalid module name ${module_name}")
        continue()
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(STRINGS "${manifest}" manifest_lines ENCODING UTF-8)
    set(section "")
    set(module_type "")
    set(type_count 0)
    foreach(line IN LISTS manifest_lines)
        string(REGEX REPLACE "[;#].*$" "" line "${line}")
        string(STRIP "${line}" line)
        if(line MATCHES "^\\[([^]]+)\\]$")
            string(STRIP "${CMAKE_MATCH_1}" section)
        elseif(section STREQUAL "Bloom" AND line MATCHES "^Type[ \t]*=[ \t]*(.*)$")
            string(STRIP "${CMAKE_MATCH_1}" module_type)
            math(EXPR type_count "${type_count} + 1")
        endif()
    endforeach()
    if(NOT type_count EQUAL 1 OR NOT module_type MATCHES "^(Core|PnP)$")
        message(WARNING "Bloom: skipping ${module_name}; expected [Bloom] Type=Core or Type=PnP")
        continue()
    endif()

    file(GLOB module_main CONFIGURE_DEPENDS "${module_dir}/main.cpp")
    file(GLOB_RECURSE module_sources CONFIGURE_DEPENDS
        "${module_dir}/src/*.cpp" "${module_dir}/src/*.cc" "${module_dir}/src/*.cxx" "${module_dir}/src/*.C")
    list(APPEND module_sources ${module_main})
    if(module_sources)
        target_sources(sprig PRIVATE ${module_sources})
        set_source_files_properties(${module_sources} PROPERTIES COMPILE_DEFINITIONS
            "BLOOM_MODULE_NAME=\"${module_name}\";BLOOM_MODULE_TYPE=::Bloom::Type::${module_type}")
    endif()
    foreach(include_dir inc include)
        if(IS_DIRECTORY "${module_dir}/${include_dir}")
            target_include_directories(sprig PRIVATE "${module_dir}/${include_dir}")
        endif()
    endforeach()

    # Hex escapes preserve arbitrary UTF-8, quotes, backslashes, and CMake semicolons.
    set(config_hex "")
    file(GLOB module_config CONFIGURE_DEPENDS "${module_dir}/config.ini")
    if(module_type STREQUAL "PnP" AND module_config)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${module_config}")
        file(READ "${module_config}" config_hex HEX)
    endif()
    string(REGEX REPLACE "(..)" "\\\\x\\1" config_literal "${config_hex}")
    string(APPEND bloom_entries "        {\"${module_name}\", Type::${module_type}, \"${config_literal}\"},\n")

    # Every dedicated non-code directory is an asset directory, regardless of name.
    file(GLOB asset_dirs CONFIGURE_DEPENDS LIST_DIRECTORIES true "${module_dir}/*")
    foreach(asset_dir IN LISTS asset_dirs)
        get_filename_component(asset_name "${asset_dir}" NAME)
        if(NOT IS_DIRECTORY "${asset_dir}" OR asset_name MATCHES "^(inc|include|src)$")
            continue()
        endif()
        file(GLOB_RECURSE asset_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${asset_dir}/*")
        if(asset_files)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${asset_files})
        endif()
        file(COPY "${asset_dir}" DESTINATION "${bloom_assets}/${module_name}")
    endforeach()
    message(STATUS "Bloom: ${module_name} (${module_type})")
endforeach()
set(bloom_content "#include <bloom/bloom.h>\nnamespace Bloom {\nstd::span<const Module> Modules() {\n")
if(bloom_entries)
    string(APPEND bloom_content "    static const Module modules[] = {\n${bloom_entries}    };\n    return modules;\n")
else()
    string(APPEND bloom_content "    return {};\n")
endif()
string(APPEND bloom_content "}\n}\n")
file(CONFIGURE OUTPUT "${bloom_generated}" CONTENT "${bloom_content}" @ONLY)
target_sources(sprig PRIVATE "${bloom_generated}")
